[package]
name = "lib_fat"
version = "0.1.0"
authors = ["Steven Tang <steven.yc.tang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"

[lib]
name = "lib_fat"
path = "src/lib.rs"
